export const StudentInfoData = [
  {
    id: 1,
    title: "info.personal",
    data: [
      { id: 1, title: "common.eng_name" },
      { id: 2, title: "common.ar_name" },
      { id: 3, title: "common.nationality" },
      { id: 4, title: "common.gender" },
      { id: 5, title: "common.religion" },
      { id: 6, title: "common.birthdate" },
      { id: 7, title: "common.birthplace" },
      { id: 8, title: "common.nationalId" },
    ],
  },
  {
    id: 2,
    title: "info.family",
    data: [
      { id: 1, title: "common.guardianName" },
      { id: 2, title: "common.guardianJob" },
      { id: 3, title: "common.city" },
      { id: 4, title: "common.gender" },
      { id: 5, title: "common.guardianAddress" },
      { id: 6, title: "common.guardianMail" },
      { id: 7, title: "common.guardianPhone" },
    ],
  },
  {
    id: 3,
    title: "info.contact",
    data: [
      { id: 1, title: "common.city" },
      { id: 2, title: "common.address" },
      { id: 3, title: "common.homeNumber" },
      { id: 4, title: "common.mail" },
      { id: 5, title: "common.box" },
      { id: 6, title: "common.phone" },
      { id: 7, title: "common.system" },
    ],
  },
  {
    id: 4,
    title: "info.pre",
    data: [
      { id: 1, title: "common.prevQualificationInstitute" },
      { id: 2, title: "common.prevQualification" },
      { id: 3, title: "common.enrollmentYear" },
      { id: 4, title: "common.enrollmentEndDate" },
      { id: 5, title: "common.totalPrevQualification" },
      { id: 6, title: "common.schoolSeat" },
      { id: 7, title: "common.precentage" },
    ],
  },
];
