name: publish

# https://stackoverflow.com/questions/57762452/react-scripts-build-is-using-1-gb-of-ram
on:
  push:
    branches:
      - publish

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: npm i

      - name: run the build script and ignore warnings
        run: CI=false npm run build

      - name: zip the build folder
        run: zip -r -q build.zip build

      - name: send the zip file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "build.zip"
          target: "/var/www/project-io.engineer/student/"

      - name: unzip the file on the destination server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            unzip -o /var/www/project-io.engineer/student/build.zip -d /var/www/project-io.engineer/student
